### ISSUE TITLE
Include examples

### ISSUE THREAD

**Issue by eshimischi** [ktsn/vuex-smart-module#1]
Hi, nice job here, would love to see an examples with some ways of usage of Vuex modules. 

Regards

**Comment by ktsn** [comment]
I'm just writing it. Please be patient, thanks 🙂

**Comment by ktsn** [comment]
Sorry for leaving for such a long time. I reconsidered the API as I realized there are some problems in the previous implementation.
I just updated the readme with the updated API.
https://github.com/ktsn/vuex-smart-module#readme
