### ISSUE TITLE
How to use with vue-class-component?

### ISSUE THREAD

**Issue by NikitaKA** [ktsn/vuex-smart-module#10]
I'm trying to do something like that:

```javascript
import foo from 'store/modules/foo';

@Component({
  methods: foo.mapMutations(['bar', 'baz'])
})
```

But got an error: `Argument types do not match parameters` on `mapMutations`.

**Comment by ilajosmanov** [comment]
You should you spread operators

**Comment by NikitaKA** [comment]
@ilajosmanov 
But in tests there are no spread operator:
```javascript
const Test = Vue.extend({
  methods: foo.mapMutations(['inc']),
  render(h): any {
    return h('div')
  }
})
```

I've tried to use spread, but that didn't help
![image](https://user-images.githubusercontent.com/2543427/54228313-f3970780-4512-11e9-9df3-2418b1944106.png)

There are no errors thrown from compiler and mutations typings do not work too.

**Comment by NikitaKA** [comment]
I found that problem appears when that's done in `.vue` file. Everything works fine when doing same thing in regular `.ts` file... Is there any way to fix this?

**Comment by ktsn** [comment]
The example code should work properly. It does not matter whether you use spread operator or not.
If you provide self-contained reproduction, we would easily find the root cause of your problem.

**Comment by NikitaKA** [comment]
@ktsn 
I have created simple project with Vue CLI for demonstration: https://github.com/NikitaKA/vuex-smart-module-bug (sorry if it's not).
Problem is not in spread operator, but in mapper and `.vue` file.

**Comment by ktsn** [comment]
- TypeScript does not infer `this` type of component from component options of decorator. So it is actually normal to produce error like `setTest does not exist`.
- If you want it to infer `this` type, you should use `Vue.extend` for mappers and inherit it.

```ts
import { Component, Vue } from 'vue-property-decorator';
import TestStore from './module';

const Super = Vue.extend({
  methods: TestStore.mapMutations(['setTest'])
})

@Component
export default class App extends Super {
  mounted() {
    this.setTest(true);
  }
}
```

**Comment by NikitaKA** [comment]
@ktsn I did right as you said, but it doesn't work. But it still works fine in a regular `.ts` file. I updated the project.

![image](https://user-images.githubusercontent.com/2543427/54270238-07348380-4590-11e9-935e-cc95b948c455.png)

**Comment by ktsn** [comment]
That is likely your editor or build environment issue. It does not happen on my side with your reproduction. Please check whether the actual build process passes type check.

**Comment by NikitaKA** [comment]
Yes, you were right - there are error. It seems that WebStorm can't recognize that... Sorry for bother you, thanks for help!
