### ISSUE TITLE
Type safety issue with actions of extended module instance

### ISSUE THREAD

**Issue by cainrus** [ktsn/vuex-smart-module#113]
Hello.
It's impossible to get action result with extended module instance.
I just created a repo with vue cli and added commit with buggy case. Can you please describe me is it a bug or is it my mistake?

https://github.com/cainrus/vuex-smart-module-extended-module-type-bug/blob/99aa7f809364f020a6735d812bb8db987a15d793/src/store/user.ts#L116

**Comment by ktsn** [comment]
Intentional. Action return type cannot be specified as they may be combined if there are multiple same name actions.
