### ISSUE TITLE
Type problem when using mapMutations

### ISSUE THREAD

**Issue by NikitaKA** [ktsn/vuex-smart-module#14]
I found strange behavior (maybe a bug?) when using mapMutations. Here is repo to reproduce: https://github.com/NikitaKA/vuex-smart-module-bug

What happening? When adding mutation to mapMutations their types become unioned:

**store.ts**
```javascript
/* … */
class TestMutations extends Mutations<TestState> {
    setTest(value: boolean) {
        this.state.test = value;
    }

    setFoo(value: string) {
        this.state.foo = value;
    }
}
/* … */
```

**app.vue**
```javascript
const Super = Vue.extend({
  methods: TestStore.mapMutations(['setTest', 'setFoo'])
});

@Component
export default class App extends Super {
  mounted() {
    this.setTest('bar'); // no type error
  }
}
```

I checked that behavior in fresh installed VSCode. And build process type check is passed too.

**Comment by ktsn** [comment]
Oh, this is indeed a but of vuex-smart-module. Thanks for reporting this!

**Comment by ktsn** [comment]
Fixed in v0.2.5

**Comment by NikitaKA** [comment]
Thank you for fixing that so fast!

**Comment by Chank1e** [comment]
@NikitaKA @ktsn 
Hey, I just can't make `mapMutations` work with `vue-property-decorator`
I did like this and it doesn't work at all
```javascript

@Component<SomeComponent>({
methods :{
   ...mapper.mapMutations(['mutation']),
}
})
export default class SomeComponent extends Vue {
 callMutation() {
   this.mutation('something')
 }
}
```

mutation is called, but it's underlined with red color in IDE
