### ISSUE TITLE
Document how to mock nested module

### ISSUE THREAD

**Issue by micgro42** [ktsn/vuex-smart-module#140]
I have a module nested in my root module and one of the root getters calls one of the nested module's getters (via the context created in `$init()`).

Could you explain and document how to best mock that nested module and its getter?

**Comment by jblotus** [comment]
Sorry for commenting on closed issue, but is there a way to mock actions inside the same module? I see we can substitute dispatch with a mock, but I am using direct property access in my actions file...ie.
this.actions.myActionName()  instead of dispatch('myActionName');

Any ideas?
