### ISSUE TITLE
npm files is not the git files

### ISSUE THREAD

**Issue by alsotang** [ktsn/vuex-smart-module#17]
https://registry.npmjs.org/vuex-smart-module/-/vuex-smart-module-0.2.5.tgz

when I download this tarball and check the `lib/index.d.ts`, the definition is old 

look like this

```ts
import { Store, StoreOptions } from 'vuex';
import { Module } from './module';
export { Getters, Mutations, Actions } from './assets';
export { Dispatch, Commit, Context } from './context';
export { registerModule, unregisterModule } from './register';
export { Module };
export declare function createStore(rootModule: Module<any, any, any, any>, options?: StoreOptions<any>): Store<any>;

```

**Comment by alsotang** [comment]
oh, seems it's right.
But the return type of createStore is `Store<any>`. Why does this work?

`console.log(store.state.nested.value) // -> hello`

so the state doesn't know it has a property `nested`?

**Comment by ktsn** [comment]
Because it is very difficult to infer entire state type. Always use it via module instance (`mapXXX` helper or `context` method) instead so that it is strictly typed.
