### ISSUE TITLE
Action types getting lost

### ISSUE THREAD

**Issue by PatrickSachs** [ktsn/vuex-smart-module#174]
Hello there,

following your recommendation to use this library over sinai I've recently been experimenting with this library.

However, I'm running into the issue that generic types & action parameters are getting lost. This is especially problematic with promises, since almost all my actions either accept parameters or sometimes even return data (e.g IDs of the created datasets)

To illustrate: This is the action "loadRoom" in the class of my "Room" store:

![image](https://user-images.githubusercontent.com/7840502/78399251-dd178e80-75f4-11ea-9fe1-090314d24652.png)

And when I use it:

![gh_missingtypes](https://user-images.githubusercontent.com/7840502/78399577-6dee6a00-75f5-11ea-9d24-42d2a13e9984.png)

How can I fix this? / What did I do wrong?

Thanks for your time!

**Comment by ktsn** [comment]
This is intentional. See #23, #113
