### ISSUE TITLE
Nuxt Module is not defined in vuex store $init method

### ISSUE THREAD

**Issue by RodionMun** [ktsn/vuex-smart-module#18]
Trying to get it work by following example:

```
axios: AxiosInstance

// Called after the module is initialized
$init(store: Store<any>): void {
  // Retain axios instance for later
  this.axios = store.$axios
  console.log(this.axios) // <--- returns undefined
}
```

After i force push it to the event loop, for better understanding a flow

```
setTimeout(() => {
  console.log(store.$axios) // <--- returns an axios instance
}, 0);
```

Then i dig it up to the `./nuxt/index.js` and it seems to me like a very big space between vuex store and nuxt-modules registration

In my project: `vuex - line 51, nuxt-modules - 158`

By now, i'm using following solution of linking store right inside vuex-module:

```
store!: Store<any>

$init (store: Store<any>): void {
  this.store = store
}

async anAsyncAction () {
  await this.store.$axios.get('/api/item')
}
```

It works, but not that perfect, for example: proxying work, but some configuration like a `prefix` doesn't

**Comment by ktsn** [comment]
Thanks for the report. Just fixed the example.
