### ISSUE TITLE
Hot Module Replacement (HMR)

### ISSUE THREAD

**Issue by Gidoont** [ktsn/vuex-smart-module#201]
Is it possible to implement HMR with vuex-smart-module?
Currently I'm trying to do something like that:
```
import { myModule} from '@store/my-module/module';

const store = createStore(new Module({
    modules: { myModule },
  }),
);

if (module['hot']) {
  module['hot'].accept(['./my-module/module'], (path) => {
    console.log('Hot updating the store, ', path);
    const myModule = require('./my-module/module').myModule;
    store.hotUpdate({ modules: { myModule } })
  })
}
```

But it does not look right and I get following error from one of my components which is using `myModule.context(this.$store);` after I change something in `myModule` to trigger HMR:

> **[Vue warn]: Error in mounted hook (Promise/async): "Error: [vuex-smart-module] The module need to be registered a store before using `Module#context` or `createMapper`"**

**Comment by ktsn** [comment]
You can use hmr from v0.4.0 (will be released today)
https://github.com/ktsn/vuex-smart-module#hot-module-replacement
