### ISSUE TITLE
Access "shared subModule" methods inside components (with context feature) from its parent Module 

### ISSUE THREAD

**Issue by nicolidin** [ktsn/vuex-smart-module#208]
Hey, firstly I would like to thank you for this lib, it's the best way we found to use vuex in typescript !

To access part of a store we use context, but it seems we can't access subModule (state, mutation, action) with the `context` vuex-smart-module feature.

To illustrate the problem we have two main modules:
```typescript
const homeStore = new Module({
  state: HomeState,
  getters: HomeGetter,
  mutations: HomeMutation,
  modules: {
    homeNodeStore: nodeStore.clone(),
    homeMemberStore: memberStore.clone()
  }
});
```
```typescript
const projectStore = new Module({
  state: ProjectState,
  getters: ProjectGetter,
  mutations: ProjectMutation,
  modules: {
   projectNodeStore: nodeStore.clone(),
   projectMemberStore: memberStore.clone()
  }
});
```
As you can see Home and Project modules have each the two same sub-modules of the same type: nodeStore and memberStore (with different instances).

So how can we access (state, mutations, actions) of these sub modules from their parents using the typescript vuex-smart-module `context`, as we do when accessing (state, getter etc) directly through module:
```typescript
homeStore.context(this.$store).(state, mutation, etc);
```
A tentative way to access subModule specific instance would be:
```typescript
projectStore.nodeStore.context(this.$store).(state, mutation, etc);
```
or with the other module: 
```typescript
homeStore.nodeStore.context(this.$store).(state, mutation, etc);
```
In js vuex syntax we could do for example: 
```typescript
this.$store.commit("projectStore/nodeStore/theMutation", payload)
```
This feature is very important when we want to share store(s) implementation (used as subStore) between multiples stores.

BTW: I first try to implement this store code implementation sharing through inheritance (of each part of a store, state, mutation, action, etc), but because of the one single extend limitation we can't do that when we want to extend multiple store (here nodeStore and memberStore).

Hoping this feature can be resolved as it would allow vuex(-smart-module) to be even better !

-------------------------------
## Edit:

I just found a way to access the subStore from the parent with the ModuleOptions class accessible from the options property inside the Module class. You can simply do: 
```typescript
this.nodeState = homeStore.options.modules!["nodeStore"].context(this.$store).state;
```
But is there a way to access the subStore from its parents with a symbol and not by dereferencing the `modules` map by the name of the subStore ( which can cause runtime errors if the name is incorrect:( )  ?

Maybe this part should be more specifed in the readMe?

**Comment by atos1990** [comment]
@ktsn, I want the same feature as @nicolidin and suggest my implimentation in PR

**Comment by ktsn** [comment]
Thank you for the feature request. You can access nested modules' contexts via `context.modules` from v0.4.0.
https://github.com/ktsn/vuex-smart-module#nested-module-context
