### ISSUE TITLE
mapActions() give IDE Error

### ISSUE THREAD

**Issue by vrn-dev** [ktsn/vuex-smart-module#214]
Hi,

I am trying to integrate this library into my Vue project and am getting IDE Error in VSCode

`No overload matches this call`

vue: 2.6.11
vuex: 3.1.3
vue-property-decorator: 8.4.1
typescript: 3.8.3

```ts
class AudioPlayerState {
...
}

class AudioPlayerActions extends Actions<AudioPlayerState, any, any, AudioPlayerActions> {
  $init() {...}
  play() {...}
  stop() {...}
}

export const audioPlayer = new Module({
  	state: AudioPlayerState,
	actions: AudioPlayerActions,
})

export const audioPlayerMappers = createMapper(audioPlayer);
```
store.index.ts
```ts
Vue.use(Vuex)

const root = new Module({
	modules: {
		audioPlayer,
	},
});

export const store = createStore(root);
```

Vue component
```
@Component({
	name: 'PhoneClient',
	methods: audioPlayerMappers.mapActions({
		play: 'play', <----- Error here
	})
})
export default class Client extends Vue {...}
```

Please guide me on how to solve this issue and if any more information is required

**Comment by ktsn** [comment]
Thank you for filing the issue.
Please provide a minimal and self-contained reproduction to confirm the issue.

See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ktsn** [comment]
Closing as no reproduction is provided.
