### ISSUE TITLE
Mistake in arguments

### ISSUE THREAD

**Issue by ilajosmanov** [ktsn/vuex-smart-module#22]
Look, I have mutation without parameters. But `commit` in action I see next error: I must pass arguments ( `{}` or `undefined` )
TypeScript: 3.4.3
![Screenshot from 2019-04-25 18-53-38](https://user-images.githubusercontent.com/18512404/56750210-eca71a00-678b-11e9-981d-6b3e178b4b01.png)
![Screenshot from 2019-04-25 19-00-17](https://user-images.githubusercontent.com/18512404/56750430-71923380-678c-11e9-9d2c-c2d64a77b7e7.png)

**Comment by ktsn** [comment]
This is unfortunately won't fix. Commit and dispatch cannot omit the payload in type level even though it can be undefined. You need to explicitly pass undefined to that.
