### ISSUE TITLE
Further plan to integrate with Nuxt

### ISSUE THREAD

**Issue by 1000ch** [ktsn/vuex-smart-module#220]
related to #29.

[Nuxt will deprecate the Vuex classic mode from v3.0](https://nuxtjs.org/guide/vuex-store/#classic-mode), and now `vuex-smart-module` requires us to use the classic mode.

I guess it might be related to the next version of Vuex and this module, but I hope `vuex-smart-module` will work with Nuxt v3 because this provides a nicer interface to make Vuex type safe.

Do you have a plan related to Nuxt or any thoughts?

**Comment by ktsn** [comment]
You can use it with modules mode with `getStoreOptions` introduced from `v0.4.0` (unreleased yet).
See the docs: https://github.com/ktsn/vuex-smart-module#using-in-nuxts-modules-mode
