### ISSUE TITLE
Mistake type

### ISSUE THREAD

**Issue by ilajosmanov** [ktsn/vuex-smart-module#23]
In first screen I response `promise<string>`
![Screenshot from 2019-04-25 19-35-31](https://user-images.githubusercontent.com/18512404/56752677-7e655600-6791-11e9-973f-515552d04674.png)

In component I see next response from this action:
![Screenshot from 2019-04-25 19-35-41](https://user-images.githubusercontent.com/18512404/56752698-8de49f00-6791-11e9-8e53-dfe8189af1d4.png)

Can we fix it?

**Comment by ktsn** [comment]
That’s intentional. Dispatch may execute multiple actions so the return type of dispatch is not able to infer.
