### ISSUE TITLE
vuex-smart-module or vuex-class

### ISSUE THREAD

**Issue by vasiasan** [ktsn/vuex-smart-module#237]
Could you explain what better to use currently for typification of vuex, this library or vuex-class? As I see all developers activity here but the community used mainly vuex-class.

**Comment by ktsn** [comment]
Well they are incomparable as the scopes are different. If you want to write a vuex store type safe way, you may want to use vuex-smart-module. If you use Vue Class component and want to bind your component and Vuex store with decorator, you may want to use vuex-class.
