### ISSUE TITLE
Type safety availability

### ISSUE THREAD

**Issue by adi-zz** [ktsn/vuex-smart-module#25]
Regarding this adapted code from the README [example](https://github.com/ktsn/vuex-smart-module#nested-modules):

```typescript
import { Getters, Module, createStore } from 'vuex-smart-module'

class NestedState {
  value = 'hello'
}

class NestedGetters extends Getters<NestedState> {
  greeting(name: string): string {
    return this.state.value + ', ' + name
  }
}

const nested = new Module({
  state: NestedState,
  getters: NestedGetters
})

const root = new Module({
  modules: {
    nested
  }
})

const store = createStore(root)

// [1]
console.log(store.state.nested.value) // -> hello
console.log(store.getters['nested/greeting']('John')) // -> hello, John

// [2]
const greeting = nested.mapGetters(['greeting']).greeting()
greeting(true) // ts error: Argument of type 'true' is not assignable to parameter of type 'string'

// [3]
root.mapGetters(['nested/greeting']) // ts error: Type 'string' is not assignable to type '"$init"'
```

1. Do we have type safety in these 2 lines? It doesn't seem like that to me. I can write `console.log(store.state.nested.fakeValue)`, `store.getters['nested/fakeGreeting']('John')` with no errors.
1. Type checking works. ✔️
1. I can't find how to access from root a getter belonging to the nested module.

Thanks

**Comment by ktsn** [comment]
1. Always use context api for type safety. Inferring root store type is impossible.
3. Same with 1, inferring another module type is impossible. Use appropriate module instead.

https://github.com/ktsn/vuex-smart-module#module-lifecycle-and-dependencies

```ts
const nestedCtx = nested.context(store)
console.log(nestedCtx.state.value)
console.log(nestedCtx.getters.greeting('John'))
```
