### ISSUE TITLE
Root module issue

### ISSUE THREAD

**Issue by ilajosmanov** [ktsn/vuex-smart-module#27]
```
const store = createStore(RootModule, {
  strict: config.isDev,
  plugins: [persistLocal.vuexPersistence.plugin],
  mutations: { ... }
});
```
When i wanna create a custom mutation ( from plugin ) - Root module rewrite my root mutations. It's a big problem. How Can I create `RESTORE_MUTATION` method what provide from plugin?

From the RootModule, I cannot create this mutation, because of this mutation must call `this.$set` method.

But, when I use the classic initialize store - it works is fine
```
new Vuex.Store({
  state: {
    count: 1,
  },
  mutations: {
    RESTORE_MUTATION: persistLocal.vuexPersistence.RESTORE_MUTATION,
  },
  plugins: [persistLocal.vuexPersistence.plugin],
});
```

How we can solve this problem?

**Comment by ktsn** [comment]
#28
