### ISSUE TITLE
Bug with mutations in nested modules

### ISSUE THREAD

**Issue by Gimanh** [ktsn/vuex-smart-module#282]
Hi! I find some bug when I tried call mutations in nested vuex-smart-module. Submodule does not take into account full namespace.

Link for reproduction: https://github.com/Gimanh/vuex-smart

Reproduction:
1. Clone and install reps.
2. See code in App.ts hook created.
3. Run `npm run serve`.
4. On the main page press `Press to increment count Foo` will work increment, then press `Press to increment count Bar` and see error in console.

**Comment by ktsn** [comment]
fixed v0.4.5
