### ISSUE TITLE
Nuxt in Vuex Store Modules mode

### ISSUE THREAD

**Issue by adi-zz** [ktsn/vuex-smart-module#29]
Does `vuex-smart-module` work with Nuxt in Vuex Store [Modules mode](https://nuxtjs.org/guide/vuex-store/#modules-mode)? Thanks

**Comment by ktsn** [comment]
I don't think it can be used in modules mode because you need to create store by using `createStore` function of vuex-smart-module.

**Comment by ilajosmanov** [comment]
@adi-zz yes, this package work with nuxt. But I must be using the old syntax for create store

**Comment by MateiNenciu** [comment]
And what will happen once Nuxt 3 will come and classic store mode will be deprecated?
