### ISSUE TITLE
duplicate getter key: $init

### ISSUE THREAD

**Issue by human211** [ktsn/vuex-smart-module#294]
I have several modules with namespaced: false.
Each of them has a $init method (in the getter class)
And when the application starts, there is the error "duplicate getter key: $ init" which is clear for me( the same names of getters->$init).
But I want namespaced to be false.

**Comment by ktsn** [comment]
Thank you for filing the issue.
Please provide a minimal and self-contained reproduction to confirm the issue.

See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by human211** [comment]
I hope there will be the chance to see that problem(in console)
https://codesandbox.io/s/green-tdd-r86bb

**Comment by human211** [comment]
I'd like to know the information above is enough for understanding the problem in order not to worry about that issue?

**Comment by ktsn** [comment]
Yeah, that's enough information to confirm, thanks. Sorry I missed your comment.
