### ISSUE TITLE
Click to definition for mapped keys

### ISSUE THREAD

**Issue by cainrus** [ktsn/vuex-smart-module#319]
Hello, @ktsn !

I don't know if you still support these project, but I will ask.
Click to definition for mapped keys is not working anymore in Idea.
https://github.com/cainrus/vuex-smart-module/commit/66abbe84e9a67c6f88f6302f144cf1d54ad039a5

Is it possible to fix it? Or maybe you can suggest a workaround?

**Comment by ktsn** [comment]
I don't think we can achieve it with string literal type. You can use `.actions` and `.mutation` to utilize type information for better editor support. https://github.com/ktsn/vuex-smart-module/pull/26

**Comment by ktsn** [comment]
Closing as the solution is already provided.
