### ISSUE TITLE
Decorators support

### ISSUE THREAD

**Issue by ilajosmanov** [ktsn/vuex-smart-module#33]
What do you think about create decorators helpers for a binding store to components?

**Comment by ktsn** [comment]
I thought about that on very beginning but decorators have no advantage in terms of typing - You cannot let type inference work between decorator type to class property type. It does not suit this lib's purpose (type safety).

If you mean you want to use it with class component, you can extend mapped component:

```ts
const Mapped = Vue.extend({
  computed: {
    ...someModule.mapGetters(['someGetter'])
  }
})

export default class MyComp extends Mapped {
  mounted() {
    console.log(this.someGetter) // `this.someGetter` will be typed
  }
}
```
