### ISSUE TITLE
tyscript lint error

### ISSUE THREAD

**Issue by not3** [ktsn/vuex-smart-module#34]
vuex version 3.1.1
tyscript lint error

`vuex-smart-module/lib/assets.d.ts(1,10):
 has no exported member 'Store'.
  > 1 | import { Store } from 'vuex';
      |          ^
    2 | import { Commit, Dispatch } from './context';
    3 | import { MappedFunction } from './module';
    4 | interface Class<T> {

vuex-smart-module/lib/context.d.ts(1,10):
has no exported member 'Store'.
  > 1 | import { Store, CommitOptions, DispatchOptions } from 'vuex';
      |          ^
    2 | import { Payload, Dispatcher, Committer } from './assets';
    3 | import { Module } from './module';
    4 | export interface Commit<M> {

vuex-smart-module/lib/context.d.ts(1,17):
has no exported member 'CommitOptions'.
  > 1 | import { Store, CommitOptions, DispatchOptions } from 'vuex';
      |                 ^
    2 | import { Payload, Dispatcher, Committer } from './assets';
    3 | import { Module } from './module';
    4 | export interface Commit<M> {

vuex-smart-module/lib/context.d.ts(1,32):
has no exported member 'DispatchOptions'.
  > 1 | import { Store, CommitOptions, DispatchOptions } from 'vuex';
      |                                ^
    2 | import { Payload, Dispatcher, Committer } from './assets';
    3 | import { Module } from './module';
    4 | export interface Commit<M> {

vuex-smart-module/lib/index.d.ts(1,10):
has no exported member 'Store'.
  > 1 | import { Store, StoreOptions } from 'vuex';
      |          ^
    2 | import { Module } from './module';
    3 | export { Getters, Mutations, Actions, inject } from './assets';
    4 | export { Dispatch, Commit, Context } from './context';

vuex-smart-module/lib/index.d.ts(1,17):
has no exported member 'StoreOptions'.
  > 1 | import { Store, StoreOptions } from 'vuex';
      |                 ^
    2 | import { Module } from './module';
    3 | export { Getters, Mutations, Actions, inject } from './assets';
    4 | export { Dispatch, Commit, Context } from './context';

  > 1 | import { Store, ModuleOptions } from 'vuex';
      |          ^
    2 | import { Module } from './module';
    3 | export declare function registerModule(store: Store<any>, path: string | string[], namespace: string | null, module: Module<any, any, any, any>, options?: ModuleOptions): void;
    4 | export declare function unregisterModule(store: Store<any>, module: Module<any, any, any, any>): void;

vuex-smart-module/lib/register.d.ts(1,17):
has no exported member 'ModuleOptions'.
  > 1 | import { Store, ModuleOptions } from 'vuex';
      |                 ^
    2 | import { Module } from './module';
    3 | export declare function registerModule(store: Store<any>, path: string | string[], namespace: string | null, module: Module<any, any, any, any>, options?: ModuleOptions): void;
    4 | export declare function unregisterModule(store: Store<any>, module: Module<any, any, any, any>): void;
`

maybe
` import { Store } from 'vuex/types'`
???

**Comment by ktsn** [comment]
It's likely because of your build config or whatever. I suspect you are aliasing some directory in your project and named it as `vuex`.
Normally you can import Vuex types by just `'vuex'`

**Comment by not3** [comment]
you're right. my root path has a folder named "vuex", thanks for your hint.
