### ISSUE TITLE
Vue 3 and typescript

### ISSUE THREAD

**Issue by smoke063** [ktsn/vuex-smart-module#347]
What's about Vue 3 ? will you provide support in the future? 
What need to do for provide  typings inside  components ? 

declare module '@vue/runtime-core' {
  // provide typings for `this.$store`
  interface ComponentCustomProperties {
    $store: Store<RootState>;
    //  $store: Store<RootState>;
  }
}

vuex-shim.d.ts

Thank You!

**Comment by ktsn** [comment]
Duplicate of #106
