### ISSUE TITLE
How to initialize default state for dynamic modules?

### ISSUE THREAD

**Issue by anton164** [ktsn/vuex-smart-module#375]
We have the following dynamic module:

```typescript
export class UserState {
  userId: string;
  profile: UserProfile;
  constructor (userId: string, profile: UserProfile) {
    this.userId = userId;
    this.profile = profile;
  }
}

// actions, mutations, etc..

export const user = new Module({
  state: UserState,
  getters: UserGetters,
  mutations: UserMutations,
  actions: UserActions,
});

```

`userId and profile` should be set dynamically since this part of the store only exists once the user has logged in.

The `registerModule` interface doesn't allow us to pass initial state for the user module, shouldn't this be possible?
```typescript
registerModule(store,
  "user",
  "user/",
  user,
);
```

**Comment by anton164** [comment]
This sort of works, but would be nice if there was a pattern for it:

```typescript
let user: Module<UserStateType, UserGetters, UserMutations, UserActions> | null = null;

export const registerUserModule = (userId: string, profile: UserProfile) => {
  class UserState implements UserStateType {
    userId = userId;
    profile = profile;
  }

  user = new Module({
    state: UserState,
    getters: UserGetters,
    mutations: UserMutations,
    actions: UserActions,
  });

  registerModule(store,
    "user",
    "user/",
    user,
  );
};

export const useUserModule = () => {
  if (user) {
    return user.context(store);
  }
  else {
    throw new Error("User module is not defined");
  }
};
```

**Comment by ktsn** [comment]
This is out of the scope of this lib since Vuex does not have such a feature. You can just define a mutation to set an initial state and call it just after the registration.

**Comment by anton164** [comment]
@ktsn Actually Vuex does support this feature. In untyped VueX, at any point in the application you can call the following: 
```javascript
  store.registerModule("user", {
    state: [{
       ...someStateThatWasLoadedAsynchronously
    }],
    mutations: {...}
  });
```

The point being that you can set the initial state of the module based on dynamic data. With your implementation this is not possible, since a dynamic module is defined "statically" as a class.

Your proposed workaround to set an initial state and call a mutation after registration is not great because this means that the typing of the module has to deal with the initial state that we don't care about, i.e.:
```typescript
export class UserState {
  userId: string | null = null;
  profile: UserProfile | null = null;
}

```
^ anywhere we use UserState we have to deal with the "null" state although we _know and ensure_ that this module is loaded with the full state dynamically.

The goal here is to have a dynamic module that is loaded dynamically with strictly typed state.

Based on your work I have created the following (draft) method which works reasonably well:
```typescript
export const dynamicModule = <S, G extends BG<S>, M extends BM<S>, A extends BA<S, G, M>>(name: string, options: {
    getters: Class<G>,
    mutations: Class<M>,
    actions: Class<A>
  }) => {
  let registeredModule: Module<S, G, M, A> | null = null;
  return {
    register: <T>(store: Store<T>, initialState: Class<S>) => {
      registeredModule = new Module({
        state: initialState,
        getters: options.getters,
        mutations: options.mutations,
        actions: options.actions,
      });

      registerModule(store, name, `${name}/`, registeredModule);
    },
    get module (): Module<S, G, M, A> {
      if (registeredModule == null) {
        throw new Error(`Dynamic ${name} module is accessed, but not registered`);
      }
      return registeredModule;
    },
  };
};
```

^ Would you consider supporting this pattern in your library? I think it's absolutely necessary to have a pattern like this to support dynamic modules. In our view code we don't want to always check whether the `userModule.profile` is loaded when the application code already ensures that it is. I would be happy to rewrite this to be closer to your API and submit a PR

**Comment by anton164** [comment]
@ktsn shall I create a pull request to demonstrate?

**Comment by steven87vt** [comment]
@ktsn bumping this because I to do this in vuex 2.x but for configuration reasons. a simple config file change and the whole app is shipped to another customer.

Traditionally I would accomplish config driven state via the vuex state property which is handled by a wrapping function.

```js
const createStore = function(config) {
return {
  namespaced: true,
  state: {
    data: {
      htmlTitleAttribute: config.htmlTitleAttribute
   },
  static: Object.freeze({
    linkToExternalSite: config.htmlHttpsLink
  }),
  // more setup...
  modules: createNamespacedModules(config)
 }
```

I disagree that state initialization is not supported by vuex and in fact argue that it is very important for anything that depends on transitions like images loaded via urls in templates. I dont have to include middleware, db and other costly infrastructure to have a fully fledge vuex backed app which mutates its presentation based on some otherwise static configuration.

```json
{
  "meta": {
    "title": "Imagination Land",
    "description": "The place with vuex component imaginations run wild"
  },
  "teamMembers": [{ "id": 1, "title": "Owner", "description": "As the chief operating member...", "assets": ["photos/customPhoto1.svg"] }]
}
```

In this application the system imports a config file, handled before webpack by a build server, deploys the site files post build to nginx out on cloud provider and once network traffic hits the app loads after the store is fully configured and the creation of the store + the seeding of values continue to be co-located & and tandem. I don't have to wait for the `App.vue` lifecycle hooks to configure the store via mutations, likewise if possible before mounting, cluttering the app startup post store creation with more store management.

```js
import {config, routes} from './config'
import {VueRouter} from 'vuex-router'

const store = createStore(config)
const router = new VueRouter({routes})
const app = createApp(store, router)

app.$mount('#app')
```

For my case a simple optional parameter to initialize the state object with on the `ModulesOptions` object is fine with me. It can be passed in as `any` type because I already know the type as I'm passing it in and casting to any type for easy of implementation is also fine.

You could simply accept the `initState` object on the constructor call to `state ? new state(initState) : {}` within `create` or expose a new interface `InitState` and calling its `init(config: T)` method in the `create` handler like the other 3 lifecycle hooks.

As an example:
```js
// my app going constructor style
class RootStateModel extends AbstractCustomStuffForDataMangling {
  public someProperty: string

  constructor(config: MyConfigObject) {
    super(config) // now i can leverage all the power of class inheritance in my setup, plus everything else.
    this.someProperty = config.model.someProperty
  }
}

// my app going interface style
class RootStateModel extends AbstractCustomStuffForDataMangling implements InitState<MyConfigObject> {
  public someProperty: string

  init(config: MyConfigObject) {
    super.do(config) // now i can leverage all the power of class inheritance in my setup, plus everything else.
    this.someProperty = config.model.someProperty
  }
}

// my app creating my root state using optional any property
export const createRootModule = function (config: MyConfigObject) {
  const rootModule = new Module({
      state: RootStateModel,
      stateInit: config as any,
      actions: RootActions,
      getters: RootGetters,
      mutations: RootMutations,
  })
}

//module.ts, new interface style
export interface InitState<T> {
  init(config: T)?: void
}

//modules.ts#29
export interface ModuleOptions<
  S,
  G extends BG<S>,
  M extends BM<S>,
  A extends BA<S, G, M>,
  Modules extends Record<string, Module<any, any, any, any, any>> = {}
> {
  namespaced?: boolean
  state?: Class<S>
  initState?: any // add any type as a pass through
  getters?: Class<G>
  mutations?: Class<M>
  actions?: Class<A>
  modules?: Modules
}
...

//modules.ts#163
create(path: string[], namespace: string): ModuleInstance {
  ...
  const {
      namespaced = true,
      state,
      initState,
      getters,
      mutations,
      actions,
      modules,
    } = this.options

...

const stateInstance = state ? new state() : {}
if(stateInstance.init && initState) {
  stateInstance.init(initState)
}

const gettersInstance = getters && initGetters(getters, this)
const mutationsInstance = mutations && initMutations(mutations, this)
const actionsInstance = actions && initActions(actions, this)

return {
  options: {
    state: stateInstance,
    ...
  }
}

// or simply
return {
      options: {
        namespaced,
        state: () => (state ? (initState ? new state(initState) : new state()) : {}),
        getters: gettersInstance && gettersInstance.getters,
        mutations: mutationsInstance && mutationsInstance.mutations,
        actions: actionsInstance && actionsInstance.actions,
        modules: children && children.options,
      },
      injectStore: combine(
        children ? children.injectStore : noop,
        gettersInstance ? gettersInstance.injectStore : noop,
        mutationsInstance ? mutationsInstance.injectStore : noop,
        actionsInstance ? actionsInstance.injectStore : noop
      ),
    }

```

**Comment by steven87vt** [comment]
@ktsn recommend reopening this and accepting #556 as the fix
