### ISSUE TITLE
BUG: TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by Evertvdw** [ktsn/vuex-smart-module#386]
Hi there,

First of all, thanks for creating this package, I went on the adventure to convert the store of a complex app to use this package to provide safe typings. After a bit of struggling I finally had it working, so I started on the unit tests. Here I ran in to a very mysterious error when creating the store:
```
 TypeError: Cannot read property 'options' of undefined

      69 | 
      70 | export default () => {
    > 71 |      const rootStore = createStore(root, {
         |                        ^
      72 |              strict: !!process.env.DEBUGGING,
      73 |      });
      74 | 

      at Object.keys.reduce.options (node_modules/vuex-smart-module/dist/vuex-smart-module.cjs.js:485:46)
          at Array.reduce (<anonymous>)
      at Module.Object.<anonymous>.Module.create (node_modules/vuex-smart-module/dist/vuex-smart-module.cjs.js:482:36)
      at Object.createStore (node_modules/vuex-smart-module/dist/vuex-smart-module.cjs.js:677:25)
      at Object.<anonymous>.exports.default (src/store/index.ts:71:20)
      at Object.<anonymous>.exports.createWrapper (test/jest/utils/wrapper.ts:32:30)
      at Object.<anonymous> (src/components/cms/pages/buttons/__tests__/MoreButton.spec.ts:6:25)
```

We use a `createWrapper` function that does some setup (like createLocalVue()) and returns a mount of the component we are testing. This function is called for every unit test to start fresh. Also in this function we create a new store instance to use with this mount. However when we ran our unit tests this creation of a new store **sometimes** fails. At one point I had two dummy unit tests of two different components, which were exactly equal in all regards. One failed, one didn't.

## Solution
After a few hours of losing my mind over this, I found a solution, which was adding `const store = createStore();`  to my `jest.setup` file. After that the error was gone. While I'm glad I can move on, it bothers me that I don't know why in the world this would fix things. Maybe this is worth looking into?

## Additional info
The line it breaks on in the createStore call is in the `Module.prototype.create` function on this line:
```
var nextNamespaced = (_a = m.options.namespaced) !== null && _a !== void 0 ? _a : true;
```

Maybe you can make sense of this behavior and it could be fixed. Otherwise this bug is for future users with the same problem.

**Comment by ktsn** [comment]
Thank you for filing the issue.
Please provide a minimal and self-contained reproduction to confirm the issue.

See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by chelentos** [comment]
@Evertvdw Hello! Can you show please how exactly you have added `const store = createStore()` to your jest setup. I'm having the same problem now and will be glad for your help.

**Comment by ktsn** [comment]
Closing as reproduction is not provided.
