### ISSUE TITLE
Access to child module from parent and from parent to child

### ISSUE THREAD

**Issue by human211** [ktsn/vuex-smart-module#387]
Hello!:)
I have a question.
I have two stores(tree, tree2). In each one has submodule **form**.
> const RootModule = new Module({
>   modules: {
>     tree: TreeModule,
>     tree2: TreeModule.clone(),
>   }
> });
> const TreeModule = new Module({
>   state: TreeModuleState,
>   actions: TreeModuleActions,
>   getters: TreeModuleGetters,
>   mutations: TreeModuleMutations,
>   modules : {
>     form: FormModule
>   }
> });

How can I get access from **form** to parent **tree** and from **tree** to child **form**?
To get access to the child I'm doing in such a way:

> $init(store: Store<any>): void {
>    //this.form = FormModule.context(store); // now it's not working correctly because each tree has its own child form.
>     this.form = (this as any).__ctx__.modules.form; // it's working, but dirty.
>   }

And now I don't know how to get access from child to parent?
Thanks for any help!)

**Comment by ktsn** [comment]
You can use context. https://github.com/ktsn/vuex-smart-module#module-lifecycle-and-dependencies

**Comment by human211** [comment]
Unfortunately it doesn't work. I wrote an example above using context. The problem is that it is not clear how to get each instance of the Form its own parent context Tree.
