### ISSUE TITLE
Vue.set() property exist type check?

### ISSUE THREAD

**Issue by d9k** [ktsn/vuex-smart-module#405]
`Vue.set( target, propertyName/index, value )`

It would be nice to have runtime check whether `propertyName/index` exists in `target`.

In similar cases I use `propertyName()` function but don't like to have repetitive code in `Vue.set()` calls.

```
/**
 * Example: `propertyName<Person>("dateOfBirth")`
 */
const propertyName = <ObjectType>(name: keyof ObjectType) => name;

export default propertyName
```

**Comment by ktsn** [comment]
Vue.set is not vuex-smart-module API but Vue core lib.
