### ISSUE TITLE
missing dependency  @vue/composition-api when installed from NPM

### ISSUE THREAD

**Issue by t-works** [ktsn/vuex-smart-module#467]
After installing recent version - 0.6.1 I get errors 

This dependency was not found:
* @vue/composition-api in ./node_modules/vuex-smart-module/dist/vuex-smart-module.esm.js

in 0.6.1 this dependency was removed but the version installed from NPM is not really 0.6.1 but 1.0 which is listed as a previous version in NPM. 
I can see the current version number in https://github.com/ktsn/vuex-smart-module/blob/master/package.json is "1".
I'm not sure if that's the reason, anyway for example in version built from

https://github.com/ktsn/vuex-smart-module/archive/refs/tags/v0.6.1.zip
/lib/composables.js has:
```javascript
import { useStore } from 'vuex';
export function createComposable(module) {
    return function useContext() {
        var store = useStore();
        return module.context(store);
    };
}
```
while /node_modules/vuex-smart-module/lib/composables.js installed via npm (both as 0.6.1 and 1):
there is:
```javascript
import { getCurrentInstance } from '@vue/composition-api';
import { assert } from './utils';
export function createComposable(module) {
    return function useContext() {
        var _a;
        var vm = (_a = getCurrentInstance()) === null || _a === void 0 ? void 0 : _a.proxy;
        assert(vm, 'Failed to get the current component instance');
        assert(vm.$store, 'Vuex store is not installed');
        return module.context(vm.$store);
    };
}
```

**Comment by ktsn** [comment]
Changed the latest tag to v1.0.0.

If you want to use 0.6.1, you need to install the dep by yourself.
