### ISSUE TITLE
Question regarding method style access / load

### ISSUE THREAD

**Issue by Bacp** [ktsn/vuex-smart-module#468]
Hi, 

I just implemented typescript and used vuex-smart-module to refactor my stores as classes.
I want the whole store to be accessible through the method style.

In the example you import the module and store and than you get the context of the module.
As follows:

```
import store from '@/store'
import ExampleModule from '@/store/modules/example'

const store = ExampleModule.context(store)
```
In some complex pages is would need 4 to 5 submodules.

I thought of the following solution and correct me if i'm wrong or if this is a bad practice.
In the root store I added the following:

```
import ExampleModule from '@/store/modules/example'
import TestModule from '@/store/modules/test'

export function useStore() {
    return {
        example: ExampleModule.context(store),
        test: TestModule.context(store),
    }
}

// component
import { useStore } from '@/store'
const store = useStore();

store.example.mutations.setExample()
```

Is the a viable solution? Or is there a better way?
What about the load of this?

**Comment by vdkrasny** [comment]
Hi, you might want to use the `createComposable` helper function for each of your modules. Take a look at [an example](https://github.com/ktsn/vuex-smart-module#composable-function)

**Comment by ghost** [comment]
Hi, thanks for the suggestion, I missed that function while reading the docs.
In the end I tried several things, the code below works, while the first example initialized the module every time the useStore function was called. This initializes it once.

```
const root = new Module({
    modules: {
        account: AccountModule
    }
})

const store = createStore(root)
export default store;

const account = AccountModule.context(store)

export function useStore() {
    return {
        account: account,
    }
}
```
