### ISSUE TITLE
How to access to vue instance from StoreActions?

### ISSUE THREAD

**Issue by saint777** [ktsn/vuex-smart-module#485]
`class StoreActions extends Actions<State, StoreGetters, StoreMutations, StoreActions>`

i have action inside StoreActions class, which uses **this._vm**

Previously i used **this._vm** to access vue instance, but now with vuex-smart-module TS gives an error that theres no **_vm**

**Comment by ktsn** [comment]
That is private property in Vuex and you should not rely on it. This lib intentionally does not expose it.
