### ISSUE TITLE
Dynamic register module

### ISSUE THREAD

**Issue by ilajosmanov** [ktsn/vuex-smart-module#6]
1. How we can be register module dynamic?
2. How use strong typing if I wanna use vuex in vue-router?

**Comment by ktsn** [comment]
1. That's what I'm thinking. I'll add a new api for it later.
2. Use context api that stated in the readme. https://github.com/ktsn/vuex-smart-module#module-lifecycle-and-dependencies

**Comment by ilajosmanov** [comment]
> 1. That's what I'm thinking. I'll add a new api for it later.
> 2. Use context api that stated in the readme. https://github.com/ktsn/vuex-smart-module#module-lifecycle-and-dependencies

But if I wanna put my store to `createRouter` function and use in any router hook. How I can do it?

**Comment by ktsn** [comment]
```ts
// modules/foo.ts
const foo = new Module({ /* ... */ })

// router.ts
function createRouter(store: Store<any>) {
  const router = new Router({
    // ...
  })

  router.beforeEach(() => {
    const ctx = foo.context(store)
    ctx.dispatch('...', { /* ... */ })

    // ...
  })
}
```

**Comment by ilajosmanov** [comment]
Thanks, works )

**Comment by ktsn** [comment]
Let's keep open until register module functionality is implemented 😄

**Comment by ilajosmanov** [comment]
Oy..sorry)

**Comment by ktsn** [comment]
I've added `registerModule` and `unregisterModule` in v0.2.2

https://github.com/ktsn/vuex-smart-module#register-module-dynamically
