### ISSUE TITLE
`Error: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by KSGitUser** [ktsn/vuex-smart-module#93]
Hi. 
I have an Error when trying to run my SPA. Can you tell me how to resolve it?

> ERROR in [at-loader] ./node_modules/vuex-smart-module/lib/assets.d.ts:22:19 
>     TS1086: An accessor cannot be declared in an ambient context.

and so on

> ERROR in [at-loader] ./node_modules/vuex-smart-module/lib/context.d.ts:40:9 
>     TS1086: An accessor cannot be declared in an ambient context.

I have installed: `"typescript":  "version": "3.5.1"`

**Comment by ktsn** [comment]
Can you provide a self-contained reproduction to confirm?

**Comment by KSGitUser** [comment]
I don't have such opportunity, because it's not open source project. But I think that as error was in vuex-smart-module, you can have any suggestion how to resolve it.

**Comment by ktsn** [comment]
I didn’t say providing your code but reproduction. Reproduction means runnable code that is minimal enough to describe / reproduce your problem. You can exclude private things and share it via GitHub, codesandbox etc.

**Comment by ktsn** [comment]
Here is useful article when creating reproduction.  https://stackoverflow.com/help/minimal-reproducible-example

**Comment by KSGitUser** [comment]
I got the reasone of Error. 
Though i have `typescript: v.3.5.1`

(some code from  `./node_modules/vuex-smart-module/lib/assets.d.ts` on [TypeScript playground](http://www.typescriptlang.org/play/index.html))

![image](https://user-images.githubusercontent.com/44057836/68746624-07e35500-060a-11ea-8ec1-f13543a3313f.png)

Here no such Error in `typescript: v. 3.6.1`. In your project you have typescript: v. 3.7.2

![image](https://user-images.githubusercontent.com/44057836/68746783-5e509380-060a-11ea-9819-26db9b7d460b.png)

**Comment by ktsn** [comment]
That looks simply not supported under ts <= 3.5. https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/#get-and-set-accessors-allowed-in-ambient-contexts

I've updated readme for supported typescript version. Thank you.
